apiVersion: apps/v1
kind: Deployment
metadata:
  name: q2-student-event
spec:
  replicas: 3

  selector:
    matchLabels:
      app: q2-student-event

  template:
    metadata:
      labels:
        app: q2-student-event

    spec:
      containers:
        - name: q2-student-event
          image: y1rd/q2-student-event:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: q2-student-event-service

spec:
  type: NodePort

  selector:
    app: q2-student-event

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30012
